services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault_container
    ports:
      - "8200:8200"
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_DEV_ROOT_TOKEN_ID=thentrees
      # Đặt VAULT_DEV_ROOT_TOKEN_ID nếu muốn token cố định
      # - VAULT_DEV_ROOT_TOKEN_ID=your-root-token
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/config:/vault/config
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
    command: server -config=/vault/config/vault.hcl
    restart: unless-stopped

volumes:
  vault-data:
  vault-config: